### ISSUE TITLE
vNext

### ISSUE THREAD

**Issue by gbtb** [gbtb/nix-stable-diffusion#17]
To-Do list

- [x] Wait for the opencv segfault fix finally landing in master https://github.com/NixOS/nixpkgs/pull/214010
- [x] Remove segfault workaround in this flake
- [ ] ~Try to use upstream ROCM packages https://github.com/NixOS/nixpkgs/issues/195412#issuecomment-1401381799~ Not worth it. torchvision is not yet supported, but more importantly torchWithRocm builds are not cached by hydra because of rocfft exceeding output limit (https://github.com/NixOS/nixpkgs/pull/214606)
- [x] Update InvokeAI to https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.5p2 and maybe reuse :eyes:  some some commits from [this fork](https://github.com/MatthewCroughan/nix-stable-diffusion)
- [x] Maybe update Automatic webui, continuing work that guys have done [here](https://github.com/gbtb/nix-stable-diffusion/issues/16)

**Comment by max-privatevoid** [comment]
Adding some TODOs I'm planning to do myself or with @MatthewCroughan here

- [ ] Fix AMD GPU support without using torch-bin
- [x] Get rid of submodule usage
- [ ] Reduce/remove overlays
- [x] Package InvokeAI properly (`nix run`-able)
- [ ] Apply https://github.com/invoke-ai/InvokeAI/commit/f0f3520bca91d3fe977f1e2b7e650661a894dd81 to improve VRAM usage (assuming there is no upstream release including this commit any time soon)
- [ ] Make a NixOS module for the InvokeAI web UI
- [ ] Support pre-downloading a list of models as part of the closure

**Comment by gbtb** [comment]
Hello, max :wave: 
Thanks for sharing your plans here.
> Fix AMD GPU support without using torch-bin

I guess, it practically means using upstream ROCM-packages ? I think using source packages is good idea as long as it doesn't mean that each user has to recompile torch from sources, because it takes a lot of time.

> Get rid of submodule usage

I've started to use submodules because at the time these UIs (and even some transitive dependencies) had impure behavior and expected writable repo directories for model caching and no simple path override mechanisms were present. Probably, since then the situation has improved, especially for InvokeAI.

> Reduce/remove overlays

Most overlays I used was because of missing packages, upstreaming some popular ones to nixpkgs might be a good way to reduce overlays size :wink:

**Comment by MatthewCroughan** [comment]
Hacked on this with @max-privatevoid at FOSDEM, a plan I have is to make a flake for AI projects, as we also managed to package https://github.com/KoboldAI/KoboldAI-Client, we also want to put the hugging face models into `/nix/store` by using a `git clone` rather than allowing the program to perform the fetching at runtime.

**Comment by crertel** [comment]
Y'all are awesome! Great work!

**Comment by MatthewCroughan** [comment]
I set up https://github.com/nixified-ai with @max-privatevoid to see if we can make this an open source project that people will contribute to. Right now the main two outputs are `invokeai-amd` and `invokeai-nvidia`.

**Comment by gbtb** [comment]
> I set up https://github.com/nixified-ai with @max-privatevoid to see if we can make this an open source project that people will contribute to. Right now the main two outputs are `invokeai-amd` and `invokeai-nvidia`.

I think there is actually a pretty good chance folks will come and participate. During ~4 months I had this repo open, couple of people came by and contribute most of the work needed to run Automatic webui. I've just had to help them finish some hard stuff. If there will be good foundation, guidelines and support tooling (e.g. pynixify) it's even more likely.

**Comment by arcnmx** [comment]
> * Get rid of submodule usage
> * Reduce/remove overlays

FWIW I've just thrown up some of my personal setup of this from last year [here](https://github.com/arcnmx/nix-stable-diffusion) ([diff](https://github.com/gbtb/nix-stable-diffusion/compare/master...arcnmx:nix-stable-diffusion:main))
I'll have to take a look at how it compares to the nixified-ai flake!

> I've started to use submodules because at the time these UIs (and even some transitive dependencies) had impure behavior and expected writable repo directories for model caching and no simple path override mechanisms were present.

Patches help here, but these are services that require at least a state/config directory. The best you generally can do is provide a skeleton dir and (optionally) prepopulate it as part of a wrapper (alternatively, provide a nixos module that does this for you in /var/lib/webui via tmpfiles and sets up a systemd service etc)

**Comment by MatthewCroughan** [comment]
@arcnmx It looks to me like anything that uses pytorch always has this `models/` folder in common, I was thinking we could populate that by making symlinks to the nix store via systemd tmpfiles in a nixosModule, that's going to be what I attempt to do in the nixified.ai repo when the time comes.

**Comment by gbtb** [comment]
Released 2.0.0 version
