### ISSUE TITLE
WebUI - allow specifying output dir

### ISSUE THREAD

**Issue by hermann-p** [gbtb/nix-stable-diffusion#26]
Currently webui tries to write to `output/log/...`, which is a read-only destination in the nix-store, when saving results. We'd need a way pass another location to the script, or if it already exists add it to the documentation.

**Comment by gbtb** [comment]
Hello :wave:  Have you tried to set paths in the settings tab of the webui ? Unfortunately, CLI doesn't offer these options, so you have to set it manually.

**Comment by hermann-p** [comment]
Hello :) Thanks, I finally found the settings in the web UI.
I still feel it should be mentioned in the how-to-get-started, as it looks like image generation was broken when the path is not set although everything works just fine.
