### ISSUE TITLE
Support for stable-diffusion-webui

### ISSUE THREAD

**Issue by RolfNic** [gbtb/nix-stable-diffusion#3]
Add support for [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
stable-diffusion-webui has far more features and community support than InvokeAI does.

**Comment by gbtb** [comment]
It's great, that you've started the branch, thank you! If you'll have troubles with packaging missing dependencies, I advice you to look into other projects I've mentioned in the readme, I think one of them has packaged this exact SD variant. And also if you'll have troubles with missing packages/versions when using pynixify, I can send you a quickhack patch I've made. This patch makes pynixify skip these errors and complete generation of files, even with some packages being "not found".
